package com.abosultan.darbakmaps.ui;

import android.app.AlertDialog;import android.content.Context;import android.content.Intent;import android.graphics.Color;import android.graphics.Typeface;import android.graphics.drawable.ColorDrawable;import android.view.Gravity;import android.view.View;import android.view.Window;import android.view.WindowManager;import android.widget.LinearLayout;import android.widget.ScrollView;import android.widget.TextView;
import com.abosultan.darbakmaps.MainActivity;import com.abosultan.darbakmaps.core.MapImportManager;import com.abosultan.darbakmaps.core.SessionStore;import com.abosultan.darbakmaps.core.TrackRecordingService;import java.io.File;

final class SettingsDialog {
 static void show(Context c){MapUiSettings s=new MapUiSettings(c);SessionStore session=new SessionStore(c);LinearLayout root=new LinearLayout(c);root.setOrientation(LinearLayout.VERTICAL);root.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);int p=DarbakUi.dp(c,18);root.setPadding(p,p,p,p);root.setBackground(DarbakUi.rounded(DarbakUi.BG,DarbakUi.ACCENT,22,c));final AlertDialog[] h=new AlertDialog[1];
  LinearLayout head=new LinearLayout(c);head.setGravity(Gravity.CENTER_VERTICAL);head.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);TextView title=text(c,"الإعدادات",25,true);TextView brand=text(c,"أبوسلطان  •  دربك",13,true);brand.setTextColor(DarbakUi.ACCENT);head.addView(title,new LinearLayout.LayoutParams(0,DarbakUi.dp(c,44),1f));head.addView(brand,new LinearLayout.LayoutParams(-2,DarbakUi.dp(c,44)));root.addView(head);
  TextView hint=text(c,"إعدادات دربك — لمس واحد للتغيير والحفظ تلقائي",12,false);hint.setTextColor(DarbakUi.TEXT_SECONDARY);root.addView(hint,wrap(c,2));
  LinearLayout cards=new LinearLayout(c);cards.setOrientation(LinearLayout.HORIZONTAL);cards.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);cards.setGravity(Gravity.TOP);root.addView(cards,new LinearLayout.LayoutParams(-1,0,1f));
  LinearLayout right=new LinearLayout(c);right.setOrientation(LinearLayout.VERTICAL);LinearLayout left=new LinearLayout(c);left.setOrientation(LinearLayout.VERTICAL);LinearLayout.LayoutParams col=new LinearLayout.LayoutParams(0,-2,1f);col.setMargins(DarbakUi.dp(c,6),DarbakUi.dp(c,10),DarbakUi.dp(c,6),0);cards.addView(right,col);cards.addView(left,col);
  File map=MapImportManager.destination(c);LinearLayout mapCard=card(c,"الخريطة",map.isFile()?map.getName()+"  •  "+formatSize(map.length()):"لا توجد خريطة معتمدة");TextView importMap=smallAction(c,map.isFile()?"استبدال الخريطة":"إضافة خريطة");importMap.setOnClickListener(v->{if(h[0]!=null)h[0].dismiss();if(c instanceof MainActivity)((MainActivity)c).pickOfflineMap();});mapCard.addView(importMap,wrap(c,6));right.addView(mapCard,wrap(c,0));
  LinearLayout display=card(c,"العرض","واجهة القيادة");addToggle(c,display,s,MapUiSettings.SPEED,"عداد السرعة");addToggle(c,display,s,MapUiSettings.MAP_TOOLS,"أدوات الخريطة");addToggle(c,display,s,MapUiSettings.BOTTOM_DOCK,"الشريط السفلي");addToggle(c,display,s,MapUiSettings.AUTO_HIDE,"إخفاء الأدوات تلقائيًا");right.addView(display,wrap(c,9));
  LinearLayout gps=card(c,"GPS والموقع","بيانات الموقع أثناء القيادة");addToggle(c,gps,s,MapUiSettings.GPS_INFO,"حالة ودقة GPS");addToggle(c,gps,s,MapUiSettings.ALTITUDE,"الارتفاع");addToggle(c,gps,s,MapUiSettings.COORDINATES,"الإحداثيات");left.addView(gps,wrap(c,0));
  LinearLayout behavior=card(c,"القيادة","التتبع والتشغيل");addToggle(c,behavior,s,MapUiSettings.TAP_HIDE,"إخفاء الأدوات بلمسة");addSessionToggle(c,behavior,session,true,"تسجيل المسار تلقائيًا");addSessionToggle(c,behavior,session,false,"تشغيل تلقائي مع الشاشة");left.addView(behavior,wrap(c,9));
  TextView close=smallAction(c,"إغلاق");close.setTextColor(DarbakUi.ACCENT);close.setOnClickListener(v->{if(h[0]!=null)h[0].dismiss();});root.addView(close,wrap(c,8));ScrollView sv=new ScrollView(c);sv.setFillViewport(true);sv.addView(root);AlertDialog d=new AlertDialog.Builder(c).setView(sv).create();h[0]=d;d.setOnShowListener(x->{Window w=d.getWindow();if(w!=null){w.setBackgroundDrawable(new ColorDrawable(Color.TRANSPARENT));w.setDimAmount(.68f);WindowManager.LayoutParams lp=w.getAttributes();lp.width=DarbakUi.dp(c,850);lp.height=DarbakUi.dp(c,545);w.setAttributes(lp);}});DarbakUi.showImmersive(d);}
 private static LinearLayout card(Context c,String title,String subtitle){LinearLayout b=new LinearLayout(c);b.setOrientation(LinearLayout.VERTICAL);b.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);int p=DarbakUi.dp(c,12);b.setPadding(p,p,p,p);b.setBackground(DarbakUi.rounded(DarbakUi.CARD,DarbakUi.BORDER,16,c));TextView t=text(c,title,18,true);t.setTextColor(DarbakUi.ACCENT);b.addView(t);TextView s=text(c,subtitle,11,false);s.setTextColor(DarbakUi.TEXT_SECONDARY);b.addView(s);return b;}
 private static void addToggle(Context c,LinearLayout b,MapUiSettings s,String key,String name){TextView r=toggle(c,name,s.get(key));r.setOnClickListener(v->{boolean n=!s.get(key);s.set(key,n);setToggle(r,name,n);});b.addView(r,wrap(c,5));}
 private static void addSessionToggle(Context c,LinearLayout b,SessionStore s,boolean recording,String name){boolean cur=recording?s.shouldResumeTrackRecording():s.shouldAutoLaunch();TextView r=toggle(c,name,cur);r.setOnClickListener(v->{boolean now=recording?s.shouldResumeTrackRecording():s.shouldAutoLaunch(),next=!now;Intent i=new Intent(c,TrackRecordingService.class);if(recording){s.setTrackRecording(next);i.setAction(next?TrackRecordingService.ACTION_RESUME:TrackRecordingService.ACTION_PAUSE);}else{s.setAutoLaunch(next);i.setAction(TrackRecordingService.ACTION_REFRESH);}try{c.startService(i);}catch(RuntimeException ignored){}setToggle(r,name,next);});b.addView(r,wrap(c,5));}
 private static TextView toggle(Context c,String name,boolean on){TextView t=text(c,"",14,true);t.setPadding(DarbakUi.dp(c,12),0,DarbakUi.dp(c,12),0);t.setGravity(Gravity.CENTER_VERTICAL|Gravity.RIGHT);setToggle(t,name,on);t.setLayoutParams(new LinearLayout.LayoutParams(-1,DarbakUi.dp(c,40)));return t;}private static void setToggle(TextView t,String name,boolean on){t.setText((on?"✓  ":"○  ")+name);t.setTextColor(on?DarbakUi.TEXT:DarbakUi.TEXT_SECONDARY);t.setBackground(DarbakUi.rounded(on?DarbakUi.ACTIVE:DarbakUi.SURFACE,on?DarbakUi.ACCENT:DarbakUi.BORDER,12,t.getContext()));}
 private static TextView smallAction(Context c,String s){TextView t=DarbakUi.action(c,s);t.setMinHeight(DarbakUi.dp(c,38));return t;}private static TextView text(Context c,String s,int sp,boolean bold){TextView t=new TextView(c);t.setText(s);t.setTextColor(DarbakUi.TEXT);t.setTextSize(sp);t.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);if(bold)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}private static LinearLayout.LayoutParams wrap(Context c,int top){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.topMargin=DarbakUi.dp(c,top);return p;}private static String formatSize(long n){if(n>=1024L*1024L)return Math.round(n/(1024d*1024d))+" MB";return Math.round(n/1024d)+" KB";}private SettingsDialog(){}
}
