package com.abosultan.darbakmaps;

import android.Manifest;import android.app.Activity;import android.content.Intent;import android.content.pm.PackageManager;import android.os.Bundle;import android.view.View;import android.view.Window;import android.view.WindowManager;import android.widget.Toast;
import com.abosultan.darbakmaps.core.MapImportManager;import com.abosultan.darbakmaps.core.TrackRecordingService;import com.abosultan.darbakmaps.ui.HomeScreen;

public final class MainActivity extends Activity {
 public static final int PICK_MAP=2601;private static final int STARTUP_PERMISSIONS=25;private static final int IMMERSIVE_FLAGS=View.SYSTEM_UI_FLAG_FULLSCREEN|View.SYSTEM_UI_FLAG_HIDE_NAVIGATION|View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY|View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN|View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION|View.SYSTEM_UI_FLAG_LAYOUT_STABLE;
 @Override protected void onCreate(Bundle b){super.onCreate(b);requestWindowFeature(Window.FEATURE_NO_TITLE);getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN,WindowManager.LayoutParams.FLAG_FULLSCREEN);applyImmersiveMode();setContentView(new HomeScreen(this));ensurePermissions();}
 @Override protected void onStart(){super.onStart();if(checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)==PackageManager.PERMISSION_GRANTED)startTrackService();}
 @Override protected void onStop(){if(checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)==PackageManager.PERMISSION_GRANTED)signalUiInactive();super.onStop();}
 public void pickOfflineMap(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("application/octet-stream");i.putExtra(Intent.EXTRA_MIME_TYPES,new String[]{"application/octet-stream","application/x-mapsforge","*/*"});startActivityForResult(i,PICK_MAP);}
 @Override protected void onActivityResult(int requestCode,int resultCode,Intent data){super.onActivityResult(requestCode,resultCode,data);if(requestCode==PICK_MAP&&resultCode==RESULT_OK&&data!=null&&data.getData()!=null){Toast.makeText(this,"جارٍ فحص الخريطة…",Toast.LENGTH_SHORT).show();final android.net.Uri uri=data.getData();new Thread(()->{boolean ok=MapImportManager.importUri(this,uri);runOnUiThread(()->{Toast.makeText(this,ok?"تم اعتماد الخريطة":"ملف الخريطة غير صالح",Toast.LENGTH_LONG).show();if(ok)setContentView(new HomeScreen(this));applyImmersiveMode();});}).start();}}
 private void ensurePermissions(){boolean gps=checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)==PackageManager.PERMISSION_GRANTED;boolean storage=checkSelfPermission(Manifest.permission.READ_EXTERNAL_STORAGE)==PackageManager.PERMISSION_GRANTED;if(gps&&storage){startTrackService();return;}java.util.ArrayList<String> m=new java.util.ArrayList<>();if(!gps)m.add(Manifest.permission.ACCESS_FINE_LOCATION);if(!storage)m.add(Manifest.permission.READ_EXTERNAL_STORAGE);requestPermissions(m.toArray(new String[0]),STARTUP_PERMISSIONS);}
 private void startTrackService(){Intent i=new Intent(this,TrackRecordingService.class);i.setAction(TrackRecordingService.ACTION_UI_ACTIVE);startService(i);}
 private void signalUiInactive(){try{Intent i=new Intent(this,TrackRecordingService.class);i.setAction(TrackRecordingService.ACTION_UI_INACTIVE);startService(i);}catch(RuntimeException ignored){}}
 @Override public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==STARTUP_PERMISSIONS&&checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)==PackageManager.PERMISSION_GRANTED)startTrackService();applyImmersiveMode();}
 @Override public void onWindowFocusChanged(boolean f){super.onWindowFocusChanged(f);if(f)applyImmersiveMode();}private void applyImmersiveMode(){getWindow().getDecorView().setSystemUiVisibility(IMMERSIVE_FLAGS);}
}
